from __future__ import annotations

from copy import deepcopy
import json
import re
import logging
import importlib
import random
import shutil
import sys
import uuid
from pathlib import Path
from typing import Any, Callable, Protocol, TypeVar, cast

from PySide6.QtCore import (
    QEvent,
    QObject,
    QPoint,
    QSize,
    QStringListModel,
    Qt,
    QThread,
    QTime,
    QTimer,
    Signal,
    Slot,
)
from PySide6.QtGui import (
    QColor,
    QIcon,
    QMouseEvent,
    QPalette,
    QPixmap,
    QResizeEvent,
    QStandardItem,
    QStandardItemModel,
    QTextCursor,
    QWheelEvent,
)
from PySide6.QtWidgets import (
    QAbstractSpinBox,
    QApplication,
    QButtonGroup,
    QCheckBox,
    QComboBox,
    QCompleter,
    QDialog,
    QDialogButtonBox,
    QFrame,
    QFormLayout,
    QGridLayout,
    QGroupBox,
    QHBoxLayout,
    QInputDialog,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QMenu,
    QMessageBox,
    QPushButton,
    QPlainTextEdit,
    QScrollArea,
    QSizePolicy,
    QHeaderView,
    QSlider,
    QSpinBox,
    QStackedWidget,
    QStyle,
    QStyledItemDelegate,
    QStyleOptionViewItem,
    QTabWidget,
    QTabBar,
    QTableWidget,
    QTableWidgetItem,
    QTextEdit,
    QTimeEdit,
    QTreeWidget,
    QTreeWidgetItem,
    QVBoxLayout,
    QWidget,
    QWizard,
    QWizardPage,
)

from ai_adventure.alchemy.ingredients import (
    COMMON_MEASUREMENT_UNITS,
    CRAFTING_INGREDIENT_CATEGORY_NAMES,
    CRAFTING_INGREDIENT_CATEGORIES,
    CRAFTING_ITEM_RARITIES,
    format_recipe_ingredients,
    is_crafting_ingredient_category,
    normalize_recipe_ingredient,
    normalize_recipe_ingredients,
)
from ai_adventure.app.api_key_store import (
    read_api_key,
    record_terms_acceptance,
    write_api_key,
)
from ai_adventure.app.app_paths import AppPaths
from ai_adventure.app.features import (
    is_ai_enabled,
    is_playtesting_build,
    is_tts_enabled,
)
from ai_adventure.app.user_settings import (
    load_app_settings,
    normalize_app_settings,
    save_app_settings,
)
from ai_adventure.ai.modes import (
    ALL_CONTENT_HARM_CATEGORIES,
    CONTENT_HARM_CATEGORY_OPTIONS,
    DEFAULT_ALLOWED_CONTENT_HARM_CATEGORIES,
    DEFAULT_MODEL_INTELLIGENCE,
    DEFAULT_MODEL_TONE,
    DEFAULT_RESPONSE_LENGTH,
    MODEL_INTELLIGENCE_OPTIONS,
    MODEL_TONE_OPTIONS,
    RESPONSE_LENGTH_OPTIONS,
    normalize_ai_mode_preferences,
)
from ai_adventure.ai.model_catalog import (
    DEFAULT_IMAGE_MODEL,
    IMAGE_MODEL_OPTIONS,
    MODEL_CATALOG_REVIEWED_DATE,
    TEXT_MODEL_OPTIONS,
    image_model_metadata,
    normalize_image_model,
    normalize_image_preferences,
    normalize_text_model,
    text_model_metadata,
)
from ai_adventure.ai.image_styles import (
    IMAGE_STYLE_OPTIONS,
    image_style_metadata,
)
from ai_adventure.inventory_sorting import sort_inventory_items
from ai_adventure.ui.story_bubbles import split_story_bubble_segments
from ai_adventure.application.asset_generation_service import AssetGenerationService
from ai_adventure.application.audio_preferences_service import AudioPreferencesService
from ai_adventure.application.new_game_service import (
    NewGameService,
    _append_ai_context_line,
    _apply_new_game_crafting_knowledge,
    _coerce_float,
    _deduplicated_ai_skills,
    _duplicate_skill_suffix,
    _fallback_starter_item_from_setup,
    _final_start_location_for_save,
    _finalized_location_aliases,
    _finalized_skills_for_save,
    _introductory_message_for_save,
    _is_player_provided_character_field,
    _new_game_calendar_genre_hint,
    _optional_int,
    _player_character_name_replacements,
    _preserve_player_character_text,
    _preserved_player_character_fields,
    _replace_location_aliases,
    _replace_location_aliases_in_travel_locations,
    _replace_whole_name,
    _starter_inventory_top_up_item,
    _starter_item_name_from_request,
    _starter_items_for_save,
    _travel_locations_for_save,
    _unique_ai_skill_name,
)
from ai_adventure.application.save_game_service import SaveGameService
from ai_adventure.application.story_turn_service import StoryTurnService
from ai_adventure.domain.rules.values import (
    bool_setting as domain_bool_setting,
    clamped_int as domain_clamped_int,
    safe_int as domain_safe_int,
)
from ai_adventure.domain.services.state_projection import refresh_calendar_time_projection
from ai_adventure.infrastructure.images import (
    DEFAULT_IMAGE_LIMIT,
    GeminiVisualAssetService,
    VisualAssetRequest,
    build_visual_asset_requests,
    find_reusable_inventory_asset,
    save_relative_image_filename,
    save_scaled_jpeg,
)


if is_ai_enabled():
    from ai_adventure.infrastructure.gemini import (
        GeminiConfigurationError,
        GeminiNarrationService,
        GeminiRequestError,
        format_story_message,
    )
else:
    GeminiNarrationService = None
    GeminiConfigurationError = RuntimeError
    GeminiRequestError = RuntimeError

    def format_story_message(text: str) -> str:
        """Returns plain story text when the AI presentation layer is excluded."""

        return text


from ai_adventure.audio.tts_settings import (
    DEFAULT_TTS_SPEED_PERCENT,
    active_voice_spec_from_audio,
    merge_custom_voices,
    normalize_custom_voices,
    normalize_narrator_voice_spec,
    normalize_tts_audio_fields,
    normalize_tts_speed_percent,
    normalize_tts_voice_mode,
    normalize_voice_blend,
    voice_display_name,
)
from ai_adventure.audio.pronunciation import (
    PronunciationMap,
    apply_pronunciation_map,
    merge_pronunciation_maps,
    normalize_pronunciation_map,
    set_authoritative_pronunciation,
)
from ai_adventure.audio.voices import (
    DEFAULT_NARRATOR_VOICE,
    assign_speaker_voices,
    available_narrator_voices,
    normalize_narrator_voice,
)
from ai_adventure.calendar_system import (
    DEFAULT_CALENDAR_SETTINGS,
    DEFAULT_START_ELAPSED_MINUTES,
    build_calendar_snapshot,
    build_month_grid,
    format_time_of_day,
    resolve_starting_calendar_minute,
)
from ai_adventure.combat import (
    COMBAT_FOCUS_LABELS,
    COMBAT_FOCUS_LEVELS,
    COMBAT_RESOLUTION_MODE_LABELS,
    COMBAT_RESOLUTION_MODES,
    COMBAT_PERSONALITIES,
    DEFAULT_ATTACK_RANGE_FEET,
    DEFAULT_BASE_ARMOR_RATING,
    DEFAULT_PLAYER_MAX_HEALTH,
    DEFAULT_UNARMED_DAMAGE,
    EQUIPMENT_SLOTS,
    attack_hit_probability,
    attack_bonus_from_skills,
    armor_rating_from_equipment,
    calculate_team_threat_levels,
    combatant_display_name,
    combat_team_defeated,
    empty_equipment,
    equipment_item_counts,
    equipped_weapon_attack_skill,
    equipped_weapon_combat_profile,
    equipped_weapon_damage,
    item_is_valid_for_slot,
    item_metadata,
    next_living_index,
    normalize_combat_preferences,
    normalize_combat_state,
    normalize_damage_expression,
    normalize_equipment,
    roll_combat_initiative,
    roll_damage_expression,
)
from ai_adventure.context.context_builder import AiContextBuilder
from ai_adventure.currency import (
    FALLBACK_CURRENCY_DENOMINATIONS,
    describe_currency_denominations,
    format_currency_amount,
)
from ai_adventure.locations import (
    calculate_travel_estimate,
    format_distance,
    format_travel_time,
    normalize_known_location,
    normalize_known_locations,
)
from ai_adventure.magic import MAGIC_CASTING_MODE_LABELS, MAGIC_CASTING_MODES
from ai_adventure.domain.events import EventApplier
from ai_adventure.domain.services.state_manager import StateManager
from ai_adventure.new_game_setup import (
    CHARACTER_PRONOUN_OPTIONS,
    DEFAULT_CHARACTER_PRONOUNS,
    DEFAULT_STARTING_WEALTH_GUIDANCE,
    GREGORIAN_CALENDAR_SETTINGS,
    SKILL_PRESET_LEVEL_PLANS,
    STARTER_INVENTORY_MIN_ITEMS,
    ai_generated_calendar_settings_or_fallback,
    build_new_game_setup_packet,
    describe_economy_examples,
    fallback_introductory_message,
    fallback_world_summary,
    merge_authoritative_starting_calendar,
    normalize_economy_examples,
    normalize_character_pronouns,
    normalize_new_game_setup,
    parse_starter_items_text,
)
from ai_adventure.narration_preferences import (
    DEFAULT_NARRATION_STYLE,
    DEFAULT_NARRATION_TENSE,
    NARRATION_STYLE_OPTIONS,
    NARRATION_TENSE_OPTIONS,
    normalize_narration_preferences,
)
from ai_adventure.notes import parse_note_tags, prefix_markdown_lines, wrap_markdown_text
from ai_adventure.new_game_templates import (
    NewGameTemplate,
    available_automatic_template_name,
    delete_new_game_template,
    load_new_game_templates,
    save_new_game_template,
    template_setup_has_changes,
)
from ai_adventure.infrastructure.sqlite import (
    DuplicateSaveTitleError,
    SaveFileOperationError,
    SaveRepository,
    SaveSummary,
)
from ai_adventure.skills.rules import MAX_SKILL_LEVEL, XP_THRESHOLDS_BY_LEVEL


LOGGER = logging.getLogger(__name__)
_T = TypeVar("_T")


GM_THINKING_FRAMES = (
    "GM is thinking.",
    "GM is thinking..",
    "GM is thinking...",
)
GM_THINKING_TIMER_INTERVAL_MS = 500
UNRESOLVED_STATUS_TEXT = "---"
# Kokoro can spend well over eight seconds on its first local synthesis while
# loading the model and phonemizer.  Keep the fallback as a true failure guard
# instead of racing normal cold-start work.
STORY_REVEAL_STALL_TIMEOUT_MS = 30_000
NPC_TURN_DELAY_MS = 2000
CONTINUE_STORY_INSTRUCTION = (
    "Continue the previous story response as though it had been longer originally. "
    "Do not treat this as a new player action. Do not invent new player-character "
    "dialogue or choices. Add concrete scene detail, NPC reaction, immediate "
    "outcome, obstacles, discoveries, or consequences already implied by the "
    "previous action."
)
TABLE_INLINE_EDITOR_HEIGHT = 30
TABLE_INLINE_EDITOR_MIN_WIDTH = 132
TABLE_CELL_HORIZONTAL_PADDING = 10
TABLE_CELL_VERTICAL_PADDING = 4
STARTER_ITEM_COLUMN_WIDTHS = (140, 132, 140, 220, 132, 150, 100)
STARTER_WEAPON_COLUMN_WIDTHS = (150, 132, 100, 96, 120, 120, 132, 132, 100)
STARTER_ARMOR_COLUMN_WIDTHS = (150, 132, 220, 132, 132, 100)
STARTING_NPC_COLUMN_WIDTHS = (150, 160, 260, 132, 100)
STARTING_LOCATION_COLUMN_WIDTHS = (180, 320, 132, 110, 180, 120)
CURRENCY_COLUMN_WIDTHS = (150, 160, 132, 100)
ECONOMY_EXAMPLE_COLUMN_WIDTHS = (220, 132, 100)
STARTING_WEALTH_COLUMN_WIDTHS = (220, 132, 100)
THEME_NAMES = {"Light", "Dark"}
SampleVoiceCallback = Callable[[str, int, int], bool]
SKILL_LEVEL_DESCRIPTIONS = {
    5: "Signature expertise - the character's strongest, defining capability.",
    4: "Expert - a major specialty the character can rely on often.",
    3: "Skilled - solid professional competence in meaningful situations.",
    2: "Trained - useful practice, but not a primary specialty.",
    1: "Familiar - basic exposure that can still matter in the right moment.",
}


from ai_adventure.ui.primitives import *  # noqa: F401,F403,E402
from ai_adventure.ui.table_helpers import *  # noqa: F401,F403,E402
from ai_adventure.ui.themes_audio import *  # noqa: F401,F403,E402
from ai_adventure.ui.new_game_form_helpers import *  # noqa: F401,F403,E402


__all__ = [
    "ALL_CONTENT_HARM_CATEGORIES",
    "AiContextBuilder",
    "Any",
    "AppPaths",
    "AssetGenerationService",
    "AudioPreferencesService",
    "CHARACTER_PRONOUN_OPTIONS",
    "COMBAT_FOCUS_LABELS",
    "COMBAT_FOCUS_LEVELS",
    "COMBAT_PERSONALITIES",
    "COMBAT_RESOLUTION_MODES",
    "COMBAT_RESOLUTION_MODE_LABELS",
    "COMMON_MEASUREMENT_UNITS",
    "CONTENT_HARM_CATEGORY_OPTIONS",
    "CONTINUE_STORY_INSTRUCTION",
    "CRAFTING_INGREDIENT_CATEGORIES",
    "CRAFTING_INGREDIENT_CATEGORY_NAMES",
    "CRAFTING_ITEM_RARITIES",
    "CURRENCY_COLUMN_WIDTHS",
    "Callable",
    "DEFAULT_ALLOWED_CONTENT_HARM_CATEGORIES",
    "DEFAULT_ATTACK_RANGE_FEET",
    "DEFAULT_BASE_ARMOR_RATING",
    "DEFAULT_CALENDAR_SETTINGS",
    "DEFAULT_CHARACTER_PRONOUNS",
    "DEFAULT_IMAGE_LIMIT",
    "DEFAULT_IMAGE_MODEL",
    "DEFAULT_MODEL_INTELLIGENCE",
    "DEFAULT_MODEL_TONE",
    "DEFAULT_NARRATION_STYLE",
    "DEFAULT_NARRATION_TENSE",
    "DEFAULT_NARRATOR_VOICE",
    "DEFAULT_PLAYER_MAX_HEALTH",
    "DEFAULT_RESPONSE_LENGTH",
    "DEFAULT_STARTING_WEALTH_GUIDANCE",
    "DEFAULT_START_ELAPSED_MINUTES",
    "DEFAULT_TTS_SPEED_PERCENT",
    "DEFAULT_UNARMED_DAMAGE",
    "DuplicateSaveTitleError",
    "ECONOMY_EXAMPLE_COLUMN_WIDTHS",
    "EQUIPMENT_SLOTS",
    "EventApplier",
    "FALLBACK_CURRENCY_DENOMINATIONS",
    "GM_THINKING_FRAMES",
    "GM_THINKING_TIMER_INTERVAL_MS",
    "GREGORIAN_CALENDAR_SETTINGS",
    "GeminiConfigurationError",
    "GeminiNarrationService",
    "GeminiRequestError",
    "GeminiVisualAssetService",
    "IMAGE_MODEL_OPTIONS",
    "IMAGE_STYLE_OPTIONS",
    "LOGGER",
    "MAGIC_CASTING_MODES",
    "MAGIC_CASTING_MODE_LABELS",
    "MAX_SKILL_LEVEL",
    "MODEL_CATALOG_REVIEWED_DATE",
    "MODEL_INTELLIGENCE_OPTIONS",
    "MODEL_TONE_OPTIONS",
    "NARRATION_STYLE_OPTIONS",
    "NARRATION_TENSE_OPTIONS",
    "NPC_TURN_DELAY_MS",
    "NarrationPlayerProtocol",
    "NewGameService",
    "NewGameTemplate",
    "Path",
    "PronunciationMap",
    "Protocol",
    "QAbstractSpinBox",
    "QApplication",
    "QButtonGroup",
    "QCheckBox",
    "QColor",
    "QComboBox",
    "QCompleter",
    "QDialog",
    "QDialogButtonBox",
    "QEvent",
    "QFormLayout",
    "QFrame",
    "QGridLayout",
    "QGroupBox",
    "QHBoxLayout",
    "QHeaderView",
    "QIcon",
    "QInputDialog",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QListWidgetItem",
    "QMainWindow",
    "QMenu",
    "QMessageBox",
    "QMouseEvent",
    "QObject",
    "QPalette",
    "QPixmap",
    "QPlainTextEdit",
    "QPoint",
    "QPushButton",
    "QResizeEvent",
    "QScrollArea",
    "QSize",
    "QSizePolicy",
    "QSlider",
    "QSpinBox",
    "QStackedWidget",
    "QStandardItem",
    "QStandardItemModel",
    "QStringListModel",
    "QStyle",
    "QStyleOptionViewItem",
    "QStyledItemDelegate",
    "QTabBar",
    "QTabWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QTextCursor",
    "QTextEdit",
    "QThread",
    "QTime",
    "QTimeEdit",
    "QTimer",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QVBoxLayout",
    "QWheelEvent",
    "QWidget",
    "QWizard",
    "QWizardPage",
    "Qt",
    "RESPONSE_LENGTH_OPTIONS",
    "RepositoryBackedWidget",
    "SKILL_LEVEL_DESCRIPTIONS",
    "SKILL_PRESET_LEVEL_PLANS",
    "STARTER_ARMOR_COLUMN_WIDTHS",
    "STARTER_INVENTORY_MIN_ITEMS",
    "STARTER_ITEM_COLUMN_WIDTHS",
    "STARTER_WEAPON_COLUMN_WIDTHS",
    "STARTING_LOCATION_COLUMN_WIDTHS",
    "STARTING_NPC_COLUMN_WIDTHS",
    "STARTING_WEALTH_COLUMN_WIDTHS",
    "STORY_REVEAL_STALL_TIMEOUT_MS",
    "SampleVoiceCallback",
    "SaveFileOperationError",
    "SaveGameService",
    "SaveRepository",
    "SaveSummary",
    "Signal",
    "Slot",
    "SoundManagerProtocol",
    "StateManager",
    "StoryTurnService",
    "TABLE_CELL_HORIZONTAL_PADDING",
    "TABLE_CELL_VERTICAL_PADDING",
    "TABLE_INLINE_EDITOR_HEIGHT",
    "TABLE_INLINE_EDITOR_MIN_WIDTH",
    "TEXT_MODEL_OPTIONS",
    "THEME_NAMES",
    "UNRESOLVED_STATUS_TEXT",
    "VisualAssetRequest",
    "XP_THRESHOLDS_BY_LEVEL",
    "_AppTableWidget",
    "_DeselectSelectedRowFilter",
    "_INVENTORY_INVARIANT_PLURALS",
    "_INVENTORY_IRREGULAR_PLURALS",
    "_INVENTORY_UNIT_ABBREVIATIONS",
    "_NarrationPlayerClass",
    "_NoCellFocusDelegate",
    "_NoWheelComboBox",
    "_NoWheelSpinBox",
    "_SoundManagerClass",
    "_TableEditorWheelFilter",
    "_TableWheelPassthroughFilter",
    "_add_combo_options",
    "_allow_selected_row_deselection",
    "_append_ai_context_line",
    "_append_currency_table_row",
    "_append_economy_example_table_row",
    "_append_starter_armor_table_row",
    "_append_starter_item_table_row",
    "_append_starter_suggestion_table_row",
    "_append_starter_weapon_table_row",
    "_append_starting_location_table_row",
    "_append_starting_npc_table_row",
    "_application_uses_dark_theme",
    "_apply_audio_settings_to_managers",
    "_apply_new_game_crafting_knowledge",
    "_bool_setting",
    "_build_season_settings",
    "_build_starter_suggestion_table",
    "_button_row",
    "_calendar_event_time_label",
    "_calendar_type_from_settings",
    "_clamped_int",
    "_coerce_float",
    "_combo_current_data_text",
    "_configure_auto_height_table",
    "_configure_inline_table",
    "_configure_responsive_form",
    "_configure_responsive_table",
    "_configure_table_wheel_passthrough",
    "_configure_wrapping_table",
    "_crafting_ingredient_catalog_choices",
    "_create_narration_player",
    "_currency_denominations_from_table",
    "_custom_voice_display_text",
    "_dark_theme_palette",
    "_dark_theme_stylesheet",
    "_deduplicated_ai_skills",
    "_duplicate_skill_suffix",
    "_economy_examples_from_table",
    "_enable_table_sorting",
    "_fallback_starter_item_from_setup",
    "_final_start_location_for_save",
    "_finalized_location_aliases",
    "_finalized_skills_for_save",
    "_introductory_message_for_save",
    "_inventory_item_display_name",
    "_inventory_location_label",
    "_inventory_quantity_display",
    "_invoke_sample_voice_callback",
    "_is_player_provided_character_field",
    "_join_list",
    "_light_theme_palette",
    "_light_theme_stylesheet",
    "_main_window_override",
    "_metadata_int",
    "_metadata_text",
    "_narrator_voice_options",
    "_new_game_calendar_genre_hint",
    "_next_available_save_title",
    "_normalize_theme_name",
    "_optional_int",
    "_player_character_name_replacements",
    "_pluralize_inventory_phrase",
    "_populate_narrator_voice_combo",
    "_preserve_player_character_text",
    "_preserved_player_character_fields",
    "_refresh_repository_calendar_time",
    "_remove_table_row_by_button",
    "_replace_location_aliases",
    "_replace_location_aliases_in_travel_locations",
    "_replace_whole_name",
    "_resize_wrapping_table_rows",
    "_resolve_speaker_cues_for_repository",
    "_resolved_skill_checks_for_context",
    "_row_for_cell_widget",
    "_safe_int",
    "_screen_content_signature",
    "_scrollable_widget",
    "_selectable_label",
    "_set_combo_to_data",
    "_set_combo_to_text",
    "_set_generated_image",
    "_set_markdown_text",
    "_set_remove_row_button",
    "_set_table_column_widths",
    "_skill_level_label",
    "_skill_xp_progress_label",
    "_slider_row",
    "_slug_for_id",
    "_sort_descending",
    "_spin_pair_row",
    "_split_list",
    "_split_loot_items",
    "_split_save_title_suffix",
    "_starter_armor_from_table",
    "_starter_inventory_top_up_item",
    "_starter_item_kind",
    "_starter_item_name_from_request",
    "_starter_items_for_save",
    "_starter_items_from_table",
    "_starter_suggestions_from_table",
    "_starter_weapons_from_table",
    "_starting_location_options_from_table",
    "_starting_location_row_for_id",
    "_starting_location_row_id_for_row",
    "_starting_locations_from_table",
    "_starting_npcs_from_table",
    "_status_label",
    "_sync_currency_base_value_row",
    "_sync_starting_location_parent_dropdowns",
    "_sync_starting_npc_location_dropdowns",
    "_table_combo_box",
    "_table_item",
    "_table_line_edit",
    "_table_row_display_name",
    "_table_spin_box",
    "_text_model_from_ai_packet",
    "_travel_locations_for_save",
    "_unique_ai_skill_name",
    "_update_sort_state",
    "_use_soft_table_selection",
    "active_voice_spec_from_audio",
    "ai_generated_calendar_settings_or_fallback",
    "annotations",
    "apply_application_theme",
    "apply_pronunciation_map",
    "armor_rating_from_equipment",
    "assign_speaker_voices",
    "attack_bonus_from_skills",
    "attack_hit_probability",
    "available_automatic_template_name",
    "available_narrator_voices",
    "build_calendar_snapshot",
    "build_month_grid",
    "build_new_game_setup_packet",
    "build_visual_asset_requests",
    "calculate_team_threat_levels",
    "calculate_travel_estimate",
    "combat_team_defeated",
    "combatant_display_name",
    "deepcopy",
    "delete_new_game_template",
    "describe_currency_denominations",
    "describe_economy_examples",
    "domain_bool_setting",
    "domain_clamped_int",
    "domain_safe_int",
    "empty_equipment",
    "equipment_item_counts",
    "equipped_weapon_attack_skill",
    "equipped_weapon_combat_profile",
    "equipped_weapon_damage",
    "fallback_introductory_message",
    "fallback_world_summary",
    "find_reusable_inventory_asset",
    "format_currency_amount",
    "format_distance",
    "format_recipe_ingredients",
    "format_story_message",
    "format_time_of_day",
    "format_travel_time",
    "image_model_metadata",
    "image_style_metadata",
    "importlib",
    "is_ai_enabled",
    "is_crafting_ingredient_category",
    "is_playtesting_build",
    "is_tts_enabled",
    "item_is_valid_for_slot",
    "item_metadata",
    "json",
    "load_app_settings",
    "load_new_game_templates",
    "logging",
    "merge_authoritative_starting_calendar",
    "merge_custom_voices",
    "merge_pronunciation_maps",
    "next_living_index",
    "normalize_ai_mode_preferences",
    "normalize_app_settings",
    "normalize_character_pronouns",
    "normalize_combat_preferences",
    "normalize_combat_state",
    "normalize_custom_voices",
    "normalize_damage_expression",
    "normalize_economy_examples",
    "normalize_equipment",
    "normalize_image_model",
    "normalize_image_preferences",
    "normalize_known_location",
    "normalize_known_locations",
    "normalize_narration_preferences",
    "normalize_narrator_voice",
    "normalize_narrator_voice_spec",
    "normalize_new_game_setup",
    "normalize_pronunciation_map",
    "normalize_recipe_ingredient",
    "normalize_recipe_ingredients",
    "normalize_text_model",
    "normalize_tts_audio_fields",
    "normalize_tts_speed_percent",
    "normalize_tts_voice_mode",
    "normalize_voice_blend",
    "parse_note_tags",
    "parse_starter_items_text",
    "prefix_markdown_lines",
    "prepare_background_ambience_directory",
    "prepare_sound_directory",
    "prepare_sound_effect_directory",
    "random",
    "re",
    "read_api_key",
    "record_terms_acceptance",
    "refresh_calendar_time_projection",
    "resolve_starting_calendar_minute",
    "roll_combat_initiative",
    "roll_damage_expression",
    "save_app_settings",
    "save_new_game_template",
    "save_relative_image_filename",
    "save_scaled_jpeg",
    "set_authoritative_pronunciation",
    "shutil",
    "sort_inventory_items",
    "split_story_bubble_segments",
    "sys",
    "template_setup_has_changes",
    "text_model_metadata",
    "uuid",
    "voice_display_name",
    "wrap_markdown_text",
    "write_api_key",
]
